### ISSUE TITLE
[Deploy] Gitlab

### ISSUE THREAD

**Issue by zigang93** [meetfranz/plugins#211] opened 2018-10-11 03:54 UTC
### Service
\
gitlab.com

### Link to your repository

https://github.com/zigang93/franz-gitlab

**Comment by indykoning** [comment] 2018-10-15 09:38
This seems like a duplicate of [#66](https://github.com/meetfranz/plugins/issues/66)
Or does this provide extra functionality?

**Closed as completed** 2020-05-19 11:58 UTC
